### ISSUE TITLE
Questions about the final evaluation results.

### ISSUE THREAD

**Issue by nuomizai** [Hyunwoo-Park-Yonsei/highway_env_RL_TD3#1]
Hi, thanks for your open-source code for applying TD3 in the highway environment. I'd like to know if this is a stable repository to apply TD3 in this env. How about the evaluation results?

**Comment by Hyunwoo-Park-Yonsei** [comment]
Hi Nuomizai, I'm not sure what stable repository means. The evaluation result wasn't good enough. It had a tendency to go straight without avoiding a collision. There could be lots of reasons(Inappropriate features and hyperparameter, Wrong implementation of TD3). Unfortunately, I'm currently working on something else. So "solving the AV problem with policy-based RL" will be delayed until at least Aug.

**Comment by nuomizai** [comment]
> Hi Nuomizai, I'm not sure what stable repository means. The evaluation result wasn't good enough. It had a tendency to go straight without avoiding a collision. There could be lots of reasons(Inappropriate features and hyperparameter, Wrong implementation of TD3). Unfortunately, I'm currently working on something else. So "solving the AV problem with policy-based RL" will be delayed until at least Aug.

Thanks for your reply. We found it hard to apply TD3 to successfully solve the highway-env with continuous action space. Looking forward to your future research.
